from datetime import datetime
import uuid
import os


def create_report(filename, file_hash, metadata, file_type, analysis=None):
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    analysis_id = str(uuid.uuid4())

    os.makedirs("reports", exist_ok=True)

    report_filename = f"reports/report_{analysis_id}.txt"

    with open(report_filename, "w", encoding="utf-8") as report:
        report.write("================================\n")
        report.write("             SPECTRA\n")
        report.write("     DIGITAL EVIDENCE REPORT\n")
        report.write("================================\n\n")

        report.write("--- ANALYSIS INFORMATION ---\n")
        report.write(f"Analysis ID: {analysis_id}\n")
        report.write(f"Analysis Time: {timestamp}\n")
        report.write(f"File Analyzed: {filename}\n\n")

        report.write("--- FILE INFORMATION ---\n")
        report.write(f"Name: {metadata['name']}\n")
        report.write(f"Size: {metadata['size']} bytes\n")
        report.write(f"Modified: {metadata['modified']}\n")
        report.write(f"Detected Type: {file_type}\n\n")

        report.write("--- SHA-256 ---\n")
        report.write(f"{file_hash}\n\n")

        if analysis:
            report.write("--- TEXT ANALYSIS ---\n")
            report.write(f"Lines: {analysis['lines']}\n")
            report.write(f"Words: {analysis['words']}\n")
            report.write(f"Characters: {analysis['characters']}\n")
            report.write(f"Empty lines: {analysis['empty_lines']}\n")

        report.write("\n================================\n")
        report.write("Generated by SPECTRA\n")
        report.write("================================\n")

    return report_filename
